backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads
site_url: https://mturco.com
display_url: https://mturco.com
logo_url: https://mturco.com/favicon.svg

collections:
  - name: reading-list
    label: Reading List
    folder: static/posts/reading-list
    create: true
    preview_path: reading-list/{{slug}}
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: Date
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        format: YYYY-MM-DD
        picker_utc: true
      - name: body
        label: Body
        widget: markdown
